/*   Do *not* directly modify this file.  It was    */
/*   generated by the Configuration Tool; any  */
/*   changes risk being overwritten.                */

/* INPUT LED_blink.cdb */

/*  Include Header File  */
#include "LED_blinkcfg.h"

/*  Config Structures */
/*  Handles  */
